boxplot(cp_2018, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Carga Paga no ano de 2018", xlab = "Carga Paga", col="white")
boxplot(cp_2017, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Carga Paga no ano de 2017", xlab = "Carga Paga", col="white")
boxplot(cp_2016, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Carga Paga no ano de 2016", xlab = "Carga Paga", col="white")
boxplot(cp_2014, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Carga Paga no ano de 2014", xlab = "Carga Paga", col="white")
boxplot(cp_global, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Carga Paga Global", xlab = "Carga Paga", col="white")
boxplot(pv_2018, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Peso Vazio no ano de 2018", xlab = "Peso Vazio", col="white")
boxplot(pv_2017, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Peso Vazio no ano de 2017", xlab = "Peso Vazio", col="white")
boxplot(pv_2016, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Peso Vazio no ano de 2016", xlab = "Peso Vazio", col="white")
boxplot(pv_2014, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Peso Vazio no ano de 2014", xlab = "Peso Vazio", col="white")
boxplot(pv_global, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Peso Vazio Global", xlab = "Peso Vazio", col="white")
boxplot(ee_2018, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Eficiência Estrutural no ano de 2018", xlab = "Eficiência Estrutural", col="white")
boxplot(ee_2017, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Eficiência Estrutural no ano de 2017", xlab = "Eficiência Estrutural", col="white")
boxplot(ee_2016, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Eficiência Estrutural no ano de 2016", xlab = "Eficiência Estrutural", col="white")
boxplot(ee_2014, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Eficiência Estrutural no ano de 2014", xlab = "Eficiência Estrutural", col="white")
boxplot(ee_global, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Eficiência Estrutural Global", xlab = "Eficiência Estrutural", col="white")
boxplot(pvoo_2018, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontuação de Voo no ano de 2018", xlab = "Pontuação de Voo", col="white")
boxplot(pvoo_2017, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontuação de Voo no ano de 2017", xlab = "Pontuação de Voo", col="white")
boxplot(pvoo_2016, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontuação de Voo no ano de 2016", xlab = "Pontuação de Voo", col="white")
boxplot(pvoo_2014, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontuação de Voo no ano de 2014", xlab = "Pontuação de Voo", col="white")
boxplot(pvoo_global, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontuação de Voo Global", xlab = "Pontuação de Voo", col="white")
boxplot(aplusr_2018, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontos de Apresentação mais Relatórios no ano de 2018", xlab = "Pontos de Apresentação mais Relatórios", col="white")
boxplot(aplusr_2017, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontos de Apresentação mais Relatórios no ano de 2017", xlab = "Pontos de Apresentação mais Relatórios", col="white")
boxplot(aplusr_2016, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontos de Apresentação mais Relatórios no ano de 2016", xlab = "Pontos de Apresentação mais Relatórios", col="white")
boxplot(aplusr_2014, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontos de Apresentação mais Relatórios no ano de 2014", xlab = "Pontos de Apresentação mais Relatórios", col="white")
boxplot(aplusr_global, varwidth=TRUE, horizontal=TRUE, main = "BoxPlot de Pontos de Apresentação mais Relatórios Global", xlab = "Pontos de Apresentação mais Relatórios", col="white")
